# Generated by Django 4.2.1 on 2023-06-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bug_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='breed',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='name',
        ),
        migrations.AddField(
            model_name='bug',
            name='bugged_Code',
            field=models.TextField(default=1, max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='fixed_Code',
            field=models.TextField(default=1, max_length=100000),
            preserve_default=False,
        ),
    ]
