# Generated by Django 4.2.1 on 2023-06-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_bug_age_bug_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bugged_Code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bug',
            name='fixed_Code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bug',
            name='language',
            field=models.CharField(max_length=100, verbose_name='Language(s)'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='subject',
            field=models.CharField(max_length=300),
        ),
    ]
